## Data Prep ##
dataset: shakespare_plays
process_fn:
  kjv: process_kjv
  shakespare_tiny:  process_default
  shakespare_plays: process_default
  

## Hyper Params ##
train_split: 0.95
batchsize: 64
context: 256
n_heads:  8
embedding_dims: 384
lr: 0.0003
dropout: 0.2
n_heads: 6
n_blocks: 6
epochs: 5000
eval_epochs: 100
#device: 'cpu'